name: flutter_html
description: A Flutter widget rendering static HTML and CSS as Flutter widgets.
version: 1.0.0
homepage: https://github.com/Sub6Resources/flutter_html

environment:
  sdk: any
  flutter: any

dependencies:
  # Plugin for parsing html
  html: any

  # Plugins for parsing css
  csslib: any
  css_colors: any

  # Plugins for rendering the <video> tag.
  video_player: any
  chewie: any

  # Plugin for rendering the <iframe> tag.
  webview_flutter: any

  # Plugins for rendering the <audio> tag.
  chewie_audio: any

  # Plugins for rendering the <svg> tag.
  flutter_svg: any

  flutter:
    sdk: flutter



flutter:

